// <auto-generated />
namespace DMS.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newprojecttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newprojecttable));
        
        string IMigrationMetadata.Id
        {
            get { return "202204220221286_new project table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
